name: agora_communication
description: Agora sdk helper package with caller screen.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1

  agora_sdk_engine:
    git:
      url: https://github.com/swayamshreemohanty/agora_sdk_engine
      ref: master # branch name

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
